force-app/main/default/objects/pca_Pet__c/pca_Pet__c.object-meta.xml
<CustomObject>
    <description>Pet tracking object</description>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pca_Pet__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>Breed of pet</description>
    <label>Breed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Airedale Terrier</fullName>
            </value>
            <value>
                <fullName>Lakeland Terrier</fullName>
            </value>
            <value>
                <fullName>Mix</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pca_Pet__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Pet Type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dog</fullName>
            </value>
            <value>
                <fullName>Cat</fullName>
            </value>
            <value>
                <fullName>Bird</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PetRecordTEST.cls
// Test class to create a Pet Record
@IsTest
public class PetRecordTEST {
    @IsTest
    static void createPet(){
        // Create Pet
        Test.startTest();
        pca_Pet__c testPet = new pca_Pet__c(
        	Name = 'Jan',
            Breed__c = 'Lakeland Terrier',
            Type__c = 'Dog'
        );
        insert testPet;
     	
        pca_Pet__c valPet = [SELECT Id, Name FROM pca_Pet__c LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(
        	'Jan',
            valPet.Name,
            'Pet name should be Jan'
        );
    }

}